"""empty message

Revision ID: f7e83d3eb9e6
Revises: c7cb3ca182cd
Create Date: 2022-07-21 15:07:03.561144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e83d3eb9e6'
down_revision = 'c7cb3ca182cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('product_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_price')
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###
