"""added more image url fields for product model

Revision ID: 9f8e5ee2c8e7
Revises: e5569be95f41
Create Date: 2022-07-06 13:23:52.635047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8e5ee2c8e7'
down_revision = 'e5569be95f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url_1', sa.String(), nullable=False))
    op.add_column('products', sa.Column('image_url_2', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url_3', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url_4', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url_5', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url_6', sa.String(), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'image_url_6')
    op.drop_column('products', 'image_url_5')
    op.drop_column('products', 'image_url_4')
    op.drop_column('products', 'image_url_3')
    op.drop_column('products', 'image_url_2')
    op.drop_column('products', 'image_url_1')
    # ### end Alembic commands ###
