"""forgot to add user_id to products

Revision ID: 586579959971
Revises: 209194678c4c
Create Date: 2022-07-06 18:20:11.093527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586579959971'
down_revision = '209194678c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
