"""added foreign keys for categories

Revision ID: 209194678c4c
Revises: 9f8e5ee2c8e7
Create Date: 2022-07-06 13:41:29.507811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209194678c4c'
down_revision = '9f8e5ee2c8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
